<link rel="stylesheet" href="<?=$this->baseUrl('/site/assets/js/bootzard-bootstrap-wizard-template/assets/font-awesome/css/font-awesome.min.css')?>">
<link rel="stylesheet" href="<?=$this->baseUrl('/site/assets/js/bootzard-bootstrap-wizard-template/assets/css/form-elements.css')?>">
<link rel="stylesheet" href="<?=$this->baseUrl('/site/assets/js/bootzard-bootstrap-wizard-template/assets/css/style.css')?>">
<div class="row">
	<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 form-box" style="border: solid 1px black;
    border-radius: 5px;">
		<form role="form" action="" method="post" class="f1" enctype="multipart/form-data">
		<h3>User Registration</h3>
			<p>Fill in the form to create a new user</p>
			<fieldset>
				<h4>User information:</h4>
				<div class="form-group">
					<label class="sr-only" for="fname">First Name</label>
					<input type="text" name="fname" placeholder="First Name" class="form-control" id="fname">
				</div>
				<div class="form-group">
					<label class="sr-only" for="lname">Last Name</label>
					<input type="text" name="lname" placeholder="Last Name" class="form-control" id="lname">
				</div>
				<div class="form-group">
					<label class="sr-only" for="org">Organization</label>
					<input type="text" name="org" placeholder="Organization" class="form-control" id="org">
				</div>
				<div class="form-group">
					<label class="sr-only" for="email">Email</label>
					<input type="text" name="email" placeholder="Email" class="form-control" id="email">
				</div>
				<div class="form-group">
					<label class="sr-only" for="pwdc">Password</label>
					<input type="password" name="pwdc" placeholder="Password" class="form-control" id="pwdc">
				</div>
				<div class="form-group">
					<label class="sr-only" for="repwd">Confirm Password</label>
					<input type="password" name="repwd" placeholder="Confirm Password" class="form-control" id="repwd">
				</div>
                <div class="f1-buttons">
                    <button type="submit" class="btn btn-submit">Register</button>
                </div>
			</fieldset>

		</form>
	</div>
</div>
<script type="text/javascript">
	$(document).ready( function() {
      	$('.f1').submit(function(){
      		
      		if($('#pwdc').val() != $('#repwd').val()){
      			alert('Your password does not match!');
      			return false;
      		}
      	})
	  
  	});

</script>