<link rel="stylesheet" href="<?=$this->baseUrl('/site/assets/js/bootzard-bootstrap-wizard-template/assets/font-awesome/css/font-awesome.min.css')?>">
<link rel="stylesheet" href="<?=$this->baseUrl('/site/assets/js/bootzard-bootstrap-wizard-template/assets/css/form-elements.css')?>">
<link rel="stylesheet" href="<?=$this->baseUrl('/site/assets/js/bootzard-bootstrap-wizard-template/assets/css/style.css')?>">
<div class="row">
	<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 form-box" style="border: solid 1px black;
    border-radius: 5px;">
		<form role="form" action="" method="post" class="f1" enctype="multipart/form-data">
		<h3>Reset password</h3>
			<p>Fill in the form to create a new password</p>
			<fieldset>
				<h4>New password:</h4>
                <div class="form-group">
                    <label class="sr-only" for="pwdc">Password</label>
                    <input type="password" name="pwdc" placeholder="Password" class="form-control" id="pwdc">
                </div>
                <div class="form-group">
                    <label class="sr-only" for="repwd">Confirm Password</label>
                    <input type="password" name="repwd" placeholder="Confirm Password" class="form-control" id="repwd">
                </div>
                <div class="f1-buttons">
                    <input type="hidden" name="token" id="token" value="<?=$_GET['token']?>">
                    <button type="submit" class="btn btn-submit">Reset password</button>
                </div>
			</fieldset>

		</form>
	</div>
</div>
<script type="text/javascript">
    $(document).ready( function() {
        $('.f1').submit(function(){

            if($('#pwdc').val() != $('#repwd').val()){
                alert('Your password does not match!');
                return false;
            }
        })

    });

</script>