<link rel="stylesheet" href="<?php echo $this->baseUrl('/site/assets/js/bootzard-bootstrap-wizard-template/assets/font-awesome/css/font-awesome.min.css')?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/site/assets/js/bootzard-bootstrap-wizard-template/assets/css/form-elements.css')?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/site/assets/js/bootzard-bootstrap-wizard-template/assets/css/style.css')?>">
<div class="row">
	<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 form-box" style="border: solid 1px black;
    border-radius: 5px;">
		<form role="form" action="" method="post" class="f1" enctype="multipart/form-data">
		<h3>Reset password</h3>
			<p>Fill in the form to create a new password</p>
			<fieldset>
				<h4>User information:</h4>
				<div class="form-group">
					<label class="sr-only" for="email">Email</label>
					<input type="text" name="email" placeholder="Email" class="form-control" id="email">
				</div>
                <div class="f1-buttons">
                    <button type="submit" class="btn btn-submit">Request new password</button>
                </div>
			</fieldset>

		</form>
	</div>
</div>