<?php
$vOnt = explode(" - ", $this->sOnt);
?>
<script>
    $(function () {
        var src = $('#results').find('img').attr('src');

        $.ajax({
            method: "POST",
            url: "<?php echo $this->baseUrl('/index/ajaxchart')?>",
            data: {term: "<?php echo $vOnt[0]?>"}
        }).done(function (msg) {
            $('#results').find('img').attr('src', msg);
            //$('#results').find('img').addClass('img-responsive');
            //$('#results').find('img').addClass('center-block');

            $('#results').find('area').each(function () {
                if ($(this).attr('type') == "term") {
                    var src = $(this).attr('href');
                    $(this).attr('href', "http://www.ebi.ac.uk/QuickGO-Old/" + src);
                    $(this).attr('target', '_blank');
                }

            })

            $('#child-terms').find('a').each(function () {
                var src = $(this).attr('href');
                $(this).attr('href', "http://www.ebi.ac.uk/QuickGO-Old/" + src);
                $(this).attr('target', '_blank');

            })

            $('#child-terms').find('img').each(function () {
                $(this).remove()

            })
        });

    })
</script>
</div></div></div>

<div class="container-fluid" role="main">
    <div class="row">
        <div class="col-xs-12">
            <div class="">
                <a href="#" onclick="window.history.back()" class="btn btn-warning">
                    <span class="glyphicon glyphicon-chevron-left"></span> Back
                </a>
                <h3>Graphs for project "<?php echo  $this->oProject->name ?>"</h3>
                <?php
                if (count($this->voSeq) > 0) {

                    ?>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Ancestor chart - <?php echo  $this->sOnt ?></h3>
                        </div>
                        <div class="panel-body" id="">

                            <div id="byontologies" class="text-center" style="padding: 15px">


                                <?php

                                $url = "https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/%7Bids%7D/chart?ids=".$vOnt[0]."&showKey=true&showIds=true&showChildren=true";

                                ?>
                                <img src="<?php echo $url?>" class="img-responsive">
                                <?php
                                //$img = file_get_contents();


                                $client = new Zend_Http_Client($url);
                                $response = $client->request();
                                $output = ($response->getBody());

                                //echo $output;

                                /*$xml = simplexml_load_string($img);

                                $body = $xml->body;

                                var_dump($body->asXML());*/

                                ?>
                            </div>
                        </div>
                    </div>

                    <!--<div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Child terms - <?php /*= $this->sOnt */?></h3>
                        </div>
                        <div class="panel-body" id="child-terms">
                            <div id="" class="" style="padding: 15px">
                                <?php /*
                                //$vOnt = explode(" - ", $this->sOnt);
                                //$img = file_get_contents("http://www.ebi.ac.uk/QuickGO/GTerm?id=" . $vOnt[0] . "&format=mini");
                                //$xml = simplexml_load_string($img);
                                //$body = $xml->body;
                                //echo($body->asXML());
                                */?>
                            </div>
                        </div>
                    </div>-->

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><?php echo  count($this->voSeq) ?> result(s) - <?php echo  $this->sOnt ?></h3>
                        </div>
                        <div class="panel-body" id="">
                            <table class="table table-bordered table-striped dataTable">
                                <thead>
                                <tr>
                                    <th>Locus tag</th>
                                    <th>Hits</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $dbBlast = new Db_BlastResult();
                                foreach ($this->voSeq as $oSeq) {
                                    ?>
                                    <tr>
                                        <td>
                                            <?php echo  str_replace(">", "", $oSeq->title) ?>
                                        </td>
                                        <td>
                                            <?php
                                            $oBlast = $dbBlast->fetchRow('id_seq = '.$oSeq->id_seq);
                                            $voGo = $oBlast->findDependentRowset('Db_BlastGo');
                                            if (count($voGo) > 0) {
                                                foreach ($voGo as $index => $oGo) {
                                                    $text = explode('[', $oGo->text);
                                                    $text = trim($text[0]);
                                                    if ($index > 0) {
                                                        ?>
                                                        <hr style="margin-top: 5px; margin-bottom: 5px;">
                                                        <?php
                                                    }
                                                    ?>
                                                    <a href="<?php echo  $this->baseUrl('/index/viewgraph/id/' . $oGo->term . '/key/' . Plugin_Util::encrypt($this->oProject->id)) ?>">
                                                        <?php echo  $oGo->term ?> - <?php echo  $text ?>
                                                    </a>

                                                    <?php
                                                }
                                            } else {
                                                ?>
                                                -
                                                <?php
                                            }
                                            ?>



                                        </td>
                                    </tr>
                                <?php  } ?>

                                </tbody>

                            </table>

                        </div>
                    </div>
                    <?php

                }
                ?>

            </div>