<?
//$dbB = new Db_BlastResult();
//$dbS = new Db_ProjSeq();
//$dbLevel = new Db_GoLevel();

//$oGo = $this->voSeq_molecular_function[0];
//$tree = $oGo->tree_top;
//$vTree = json_decode($tree);


/*$vMF = array();
$vMFF = array();
if (count($this->voSeq_molecular_function) > 0) {
    foreach ($this->voSeq_molecular_function as $oMF) {
        $vMF[$oMF->term] += 1;
        $vMFF[$oMF->term." - ".$oMF->name] += 1;
    }
}

$vCC = array();
$vCCF = array();
if (count($this->voSeq_cellular_component) > 0) {
    foreach ($this->voSeq_cellular_component as $oCC) {
        $vCC[$oCC->term] += 1;
        $vCCF[$oCC->term." - ".$oCC->name] += 1;
    }
}

$vBP = array();
$vBPF = array();
if (count($this->voSeq_biological_process) > 0) {
    foreach ($this->voSeq_biological_process as $oBP) {
        $vBP[$oBP->term] += 1;
        $vBPF[$oBP->term." - ".$oBP->name] += 1;
    }
}*/

/*asort($vMF);
asort($vMFF);
asort($vCC);
asort($vCCF);
asort($vBP);
asort($vBPF);*/

?>
<!-- Chart code -->
<script>
    $(function () {
        var chartByOntologies = AmCharts.makeChart("byontologies", {
            "type": "pie",
            "theme": "light",
            "legend": {
                "position": "right",
                "marginRight": 100,
                "autoMargins": false
            },
            "dataProvider": [
                <?
                foreach($this->voSeq_all as $index=>$oSeq){
                    if($index>0){
                        ?>
                ,
                        <?
                    }
                    ?>
                {
                    "ontologie": "<?=$oSeq->last_parent_name?>",
                    "seqs": <?=$oSeq->hits?>
                }
                    <?
                }
                ?>],
            "valueField": "seqs",
            "titleField": "ontologie",
            "balloon": {
                "fixedPosition": true
            },
            "export": {
                "enabled": true
            }
        });

        var chartMF = AmCharts.makeChart("molecular_function", {
            "type": "serial",
            "theme": "light",
            "dataProvider": [ <?
                if(count($this->voSeq_molecular_function_detailed)){
                foreach ($this->voSeq_molecular_function_detailed as $ont){
                ?>
                {
                    "ontologie": "<?=$ont->term?>\n<?=$ont->text?>",
                    "seqs": <?=$ont->hits?>
                },

                <?
                }
                }
                ?> ],
            "valueAxes": [{
                "gridColor": "#FFFFFF",
                "gridAlpha": 0.2,
                "dashLength": 0
            }],
            "gridAboveGraphs": true,
            "startDuration": 0,
            "graphs": [{
                "balloonText": "[[category]]: <b>[[value]]</b>",
                "fillAlphas": 0.8,
                "lineAlpha": 0.2,
                "type": "column",
                "valueField": "seqs"
            }],
            "chartScrollbar": {
                "autoGridCount": true,
                "scrollbarHeight": 40
            },
            "chartCursor": {
                "categoryBalloonEnabled": false,
                "cursorAlpha": 0,
                "zoomable": true,
            },
            "categoryField": "ontologie",
            "categoryAxis": {
                "gridPosition": "start",
                "gridAlpha": 0,
                "tickPosition": "start",
                "tickLength": 20,
                "labelRotation": 90
            },
            "export": {
                "enabled": true
            }

        });

        var cloudMF = [ <?
            if(count($this->voSeq_molecular_function_detailed)){
                foreach ($this->voSeq_molecular_function_detailed as $ont){

                ?>
                {
                    "text": "<?=$ont->text?>",
                    "weight": <?=$ont->hits?>
                },

                <?
                }
            }
            ?> ];

        var chartCC = AmCharts.makeChart("cellular_component", {
            "type": "serial",
            "theme": "light",
            "dataProvider": [ <?
                if(count($this->voSeq_cellular_component_detailed)){
                foreach ($this->voSeq_cellular_component_detailed as $ont){
                ?>
                {
                    "ontologie": "<?=$ont->term?>\n<?=$ont->text?>",
                    "seqs": <?=$ont->hits?>
                },

                <?
                }
                }
                ?> ],
            "valueAxes": [{
                "gridColor": "#FFFFFF",
                "gridAlpha": 0.2,
                "dashLength": 0
            }],
            "gridAboveGraphs": true,
            "startDuration": 0,
            "graphs": [{
                "balloonText": "[[category]]: <b>[[value]]</b>",
                "fillAlphas": 0.8,
                "lineAlpha": 0.2,
                "type": "column",
                "valueField": "seqs"
            }],
            "chartScrollbar": {
                "autoGridCount": true,
                "scrollbarHeight": 40
            },
            "chartCursor": {
                "categoryBalloonEnabled": false,
                "cursorAlpha": 0,
                "zoomable": true,
            },
            "categoryField": "ontologie",
            "categoryAxis": {
                "gridPosition": "start",
                "gridAlpha": 0,
                "tickPosition": "start",
                "tickLength": 20,
                "labelRotation": 90
            },
            "export": {
                "enabled": true
            }

        });

        var cloudCC = [
            <?
            if(count($this->voSeq_cellular_component_detailed)){
                foreach ($this->voSeq_cellular_component_detailed as $ont){
                ?>
                {
                    "text": "<?=$ont->text?>",
                    "weight": <?=$ont->hits?>
                },
                <?
                }
            }
            ?>
        ];

        var chartBP = AmCharts.makeChart("biological_process", {
            "type": "serial",
            "theme": "light",
            "dataProvider": [ <?
                if(count($this->voSeq_biological_process_detailed)){
                foreach ($this->voSeq_biological_process_detailed as $ont){
                ?>
                {
                    "ontologie": "<?=$ont->term?>\n<?=$ont->text?>",
                    "seqs": <?=$ont->hits?>
                },

                <?
                }
                }
                ?> ],
            "valueAxes": [{
                "gridColor": "#FFFFFF",
                "gridAlpha": 0.2,
                "dashLength": 0
            }],
            "gridAboveGraphs": true,
            "startDuration": 0,
            "graphs": [{
                "balloonText": "[[category]]: <b>[[value]]</b>",
                "fillAlphas": 0.8,
                "lineAlpha": 0.2,
                "type": "column",
                "valueField": "seqs"
            }],
            "chartScrollbar": {
                "autoGridCount": true,
                "scrollbarHeight": 40
            },
            "chartCursor": {
                "categoryBalloonEnabled": false,
                "cursorAlpha": 0,
                "zoomable": true,
            },
            "categoryField": "ontologie",
            "categoryAxis": {
                "gridPosition": "start",
                "gridAlpha": 0,
                "tickPosition": "start",
                "tickLength": 20,
                "labelRotation": 90
            },
            "export": {
                "enabled": true
            }

        });

        var cloudBP = [
            <?
            if(count($this->voSeq_biological_process_detailed)){
                foreach ($this->voSeq_biological_process_detailed as $ont){
                ?>
                {
                    "text": "<?=$ont->text?>",
                    "weight": <?=$ont->hits?>
                },
                <?
                }
            }
            ?>
        ];

        $('.dataTableFull').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ],
            initComplete: function () {
                var table = this.api();
                this.api().columns().every(function () {
                    var column = this;
                    var select = $('<select class="updatechart"><option value=""></option></select>')
                        .appendTo($(column.footer()).empty())
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );
                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                            var dataProvider = [];
                            var ontology = [];
                            var hits = [];

                            table.column(0, {search: 'applied'}).data().each(function (d, j) {
                                var ont = $(d).html();
                                ont = ont.split("-");
                                ont = ont[0];
                                ont = ont.trim();
                                ontology.push(ont);
                            })

                            table.column(1, {search: 'applied'}).data().each(function (d, j) {
                                var hit = d;
                                hits.push(d);
                            })

                            for (var i = 0; i < ontology.length; i++) {
                                dataProvider.push({
                                    "ontologie": ontology[i],
                                    "seqs": hits[i]
                                })
                            }

                            dataProvider = dataProvider.sort(function (a, b) {
                                return a.seqs - b.seqs;
                            });

                            eval($(this).parent().parent().parent().parent().attr('id')).dataProvider = dataProvider;
                            eval($(this).parent().parent().parent().parent().attr('id')).validateData();


                        });

                    column.data().unique().sort(function (a, b) {
                        return a - b;
                    }).each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            }
        });

        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            var target = $(e.target).attr("href") // activated tab
            console.log(target);
            if(target=='#profile'){
                $("#cloud_molecular_function").jQCloud(cloudMF);
            }
            if(target=='#messages'){
                $("#cloud_cellular_component").jQCloud(cloudCC);
            }
            if(target=='#settings'){
                $("#cloud_biological_process").jQCloud(cloudBP);
            }


        })
    });

</script>

<style>
    .modal-body {
        word-wrap: break-word;
        white-space: normal;
    }

    table > tr > th {
        word-wrap: break-word;
        word-break: break-all;
        white-space: normal;
    }

    .chart {
        width: 100%;
        height: 500px;
        padding-top: 30px;
    }

    .chart-bar {
        height: 800px;
        padding-top: 30px;
        margin-bottom: 40px;
    }

    .amcharts-export-menu {
        margin-top: -40px;
    }

    .orgdiagram, .ui-widget {
        height: 100%;
    }

    .bp-photo-frame, .bp-description {

    }

    .bt-item-frame {
        border: solid 1px black;
    }

    .bp-title-frame {
        background: none !important;
        position: absolute;
        top: 0;
        bottom: 0;
        margin: auto;
    }

    .bp-title {
        color: black !important;
        text-align: center;
    }

    tfoot select {
        width: 100%;
    }

    tfoot > tr > th:first-child select, tfoot > tr > th:nth-child(2) select {
        display: none;
    }

    .locus_hits{
        max-height: 103px;
        overflow: auto;
    }
</style>
</div></div></div>
<div class="container-fluid" role="main">
    <div class="row">
        <div class="col-xs-12">
            <div class="">

                <h3>Charts for project "<?= $this->oProject->name ?>"</h3>



                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist" style="margin-bottom: 15px">
                    <li role="presentation" class="active">
                        <a href="#home" aria-controls="home" role="tab" data-toggle="tab">Summary</a>
                    </li>
                    <li role="presentation">
                        <a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Molecular function</a>
                    </li>
                    <li role="presentation">
                        <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Cellular component</a>
                    </li>
                    <li role="presentation">
                        <a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Biological process</a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        <table class="table table-bordered table-striped dataTableFull" id="chartByOntologies">
                            <thead>
                            <tr>
                                <th class="col-xs-11">Ontology</th>
                                <th class="col-xs-1">Hits</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?
                            foreach ($this->voSeq_all as $oSeq){
                                ?>
                                <tr>
                                    <td>
                                        <a href="<?= $this->baseUrl('/index/viewgraph/id/'.$oSeq->last_parent_id.'/type/parent/key/' . Plugin_Util::encrypt($this->oProject->id)) ?>">
                                            <?=$oSeq->last_parent_name?>
                                        </a>

                                    </td>
                                    <td>
                                        <?= $oSeq->hits ?>
                                    </td>
                                </tr>
                                <?
                            }
                            ?>
                            </tbody>
                        </table>
                        <div id="byontologies" class="chart"></div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="profile">
                        <div id="content-molecular_function" style="">
                            <h4>Most frent GO terms</h4>
                            <div id="cloud_molecular_function" class="col-xs-12" style="height: 500px;"></div>
                            <table class="table table-bordered table-striped dataTableFull" id="chartMF">
                                <thead>
                                <tr>
                                    <th class="col-xs-4">Ontology</th>
                                    <th class="col-xs-1">Hits</th>
                                    <th class="col-xs-1">GO Lvl (min)</th>
                                    <th class="col-xs-1">GO Lvl (max)</th>
                                    <th class="col-xs-6">Locus tags</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?
                                if (count($this->voSeq_molecular_function_detailed)) {
                                    foreach ($this->voSeq_molecular_function_detailed as $ont) {
                                        if($ont->text){
                                            ?>
                                            <tr>
                                                <td>
                                                    <a href="<?= $this->baseUrl('/index/viewgraph/id/' . $ont->term . '/key/' . Plugin_Util::encrypt($this->oProject->id)) ?>">
                                                        <?= $ont->text ?>
                                                    </a>

                                                </td>
                                                <td>
                                                    <?= $ont->hits ?>
                                                </td>
                                                <td>
                                                    <?= $ont->min ? $ont->min : "0" ?>
                                                </td>
                                                <td>
                                                    <?= $ont->max ? $ont->max : "0" ?>
                                                </td>
                                                <td>
                                                    <div class="locus_hits">
                                                        <?= str_replace(";",";<br>", $ont->locus) ?>
                                                    </div>
                                                </td>
                                            </tr>
                                            <?
                                        }

                                    }
                                }
                                ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </tfoot>
                            </table>
                            <div id="molecular_function" class="chart chart-bar"></div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="messages">
                        <div id="content-cellular_component" style="">
                            <h4>Most frent GO terms</h4>
                            <div id="cloud_cellular_component" class="col-xs-12" style="height: 500px;"></div>
                            <table class="table table-bordered table-striped dataTableFull" id="chartCC">
                                <thead>
                                <tr>
                                    <th class="col-xs-4">Ontology</th>
                                    <th class="col-xs-1">Hits</th>
                                    <th class="col-xs-1">GO Lvl (min)</th>
                                    <th class="col-xs-1">GO Lvl (max)</th>
                                    <th class="col-xs-6">Locus tags</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?
                                if (count($this->voSeq_cellular_component_detailed)) {
                                    foreach ($this->voSeq_cellular_component_detailed as $ont) {
                                        if($ont->text){
                                            ?>
                                            <tr>
                                                <td>
                                                    <a href="<?= $this->baseUrl('/index/viewgraph/id/' . $ont->term . '/key/' . Plugin_Util::encrypt($this->oProject->id)) ?>">
                                                        <?= $ont->text ?>
                                                    </a>

                                                </td>
                                                <td>
                                                    <?= $ont->hits ?>
                                                </td>
                                                <td>
                                                    <?= $ont->min ? $ont->min : "0" ?>
                                                </td>
                                                <td>
                                                    <?= $ont->max ? $ont->max : "0" ?>
                                                </td>
                                                <td>
                                                    <div class="locus_hits">
                                                        <?= str_replace(";",";<br>", $ont->locus) ?>
                                                    </div>
                                                </td>
                                            </tr>
                                            <?
                                        }


                                    }
                                }
                                ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </tfoot>
                            </table>
                            <div id="cellular_component" class="chart chart-bar"></div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="settings">

                        <div id="content-biological_process" style="">
                            <h4>Most frent GO terms</h4>
                            <div id="cloud_biological_process" class="col-xs-12" style="height: 500px;"></div>
                            <table class="table table-bordered table-striped dataTableFull" id="chartBP">
                                <thead>
                                <tr>
                                    <th class="col-xs-4">Ontology</th>
                                    <th class="col-xs-1">Hits</th>
                                    <th class="col-xs-1">GO Lvl (min)</th>
                                    <th class="col-xs-1">GO Lvl (max)</th>
                                    <th class="col-xs-6">Locus tags</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?
                                if (count($this->voSeq_biological_process_detailed)) {
                                    foreach ($this->voSeq_biological_process_detailed as $ont) {
                                        if($ont->text){
                                            ?>
                                            <tr>
                                                <td>
                                                    <a href="<?= $this->baseUrl('/index/viewgraph/id/' . $ont->term . '/key/' . Plugin_Util::encrypt($this->oProject->id)) ?>">
                                                        <?= $ont->text ?>
                                                    </a>

                                                </td>
                                                <td>
                                                    <?= $ont->hits ?>
                                                </td>
                                                <td>
                                                    <?= $ont->min ? $ont->min : "0" ?>
                                                </td>
                                                <td>
                                                    <?= $ont->max ? $ont->max : "0" ?>
                                                </td>
                                                <td>
                                                    <div class="locus_hits">
                                                        <?= str_replace(";",";<br>", $ont->locus) ?>
                                                    </div>
                                                </td>
                                            </tr>
                                            <?
                                        }


                                    }
                                }
                                ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </tfoot>
                            </table>
                            <div id="biological_process" class="chart chart-bar"></div>
                        </div>
                    </div>
                </div>
            </div>