<div class="row">
    <div class="col-xs-12">
        <?= $this->cadastrar('/painel/banner/inserealtera/') ?>
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-settings font-dark"></i>
                    <span class="caption-subject bold uppercase">Banner Home</span>
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                <?php
                if ($this->voRegistro) {
                    ?>
                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_1">
                        <thead>
                        <tr>
                            <th class="all">Imagem</th>
                            <th class="all">Título </th>
                            <th class="all sorting_disabled opcoes-header">Opções</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->voRegistro as $oRegistro) {
                            ?>
                            <tr>
                                <td>
                                    <?
                                    if($oRegistro->arquivo && file_exists($_SERVER['DOCUMENT_ROOT'].'/data/'.$oRegistro->arquivo)){
                                        ?>
                                        <img src="/data/<?=$oRegistro->arquivo?>" class="img-responsive" style="max-width: 200px">
                                        <?
                                    }
                                    ?>
                                </td>
                                <td>
                                    <?=$oRegistro->titulo?>
                                </td>
                                <td class="opcoes-tbody">
                                    <?= $this->editar('/painel/banner/inserealtera/id/' . $oRegistro->id) ?>
                                    <?= $this->excluir('/painel/banner/excluir/id/' . $oRegistro->id) ?>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>
                    <?
                }
                ?>

            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
