<div class="portlet light bordered form-fit">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-equalizer font-green-haze"></i>
            <span class="caption-subject font-green-haze bold uppercase"><?= $this->form->getAttrib('name') ?></span>
            <span class="caption-helper">Preencha os campos do formulário</span>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <?= $this->render('includes/form.phtml') ?>
        <!-- END FORM-->
    </div>
</div>

<?
if($this->oRegistro->arquivo && file_exists($_SERVER['DOCUMENT_ROOT'].'/data/'.$this->oRegistro->arquivo)){
    ?>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN Portlet PORTLET-->
            <div class="portlet light">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-picture font-green-haze"></i>
                        <span class="caption-subject bold uppercase">Imagem cadastrada</span>
                    </div>
                    <div class="actions">
                        <a href="/painel/index/excluirimg/arquivo/<?=$this->oRegistro->arquivo?>/url/<?=base64_encode("http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI])?>" class="btn btn-circle red-sunglo ">
                            <i class="fa fa-trash-o"></i> Excluir </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <img src="/data/<?=$this->oRegistro->arquivo?>" class="img-responsive">
                </div>
            </div>
            <!-- END Portlet PORTLET-->
        </div>
    </div>

    <?
}
?>
<?
if($this->oRegistro->arquivo_m && file_exists($_SERVER['DOCUMENT_ROOT'].'/data/'.$this->oRegistro->arquivo_m)){
    ?>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN Portlet PORTLET-->
            <div class="portlet light">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-picture font-green-haze"></i>
                        <span class="caption-subject bold uppercase">Imagem cadastrada (mobile)</span>
                    </div>
                    <div class="actions">
                        <a href="/painel/index/excluirimg/arquivo/<?=$this->oRegistro->arquivo_m?>/url/<?=base64_encode("http://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI])?>" class="btn btn-circle red-sunglo ">
                            <i class="fa fa-trash-o"></i> Excluir </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <img src="/data/<?=$this->oRegistro->arquivo_m?>" class="img-responsive">
                </div>
            </div>
            <!-- END Portlet PORTLET-->
        </div>
    </div>

    <?
}
?>
