<?php
if ($this->estrutura) {
    foreach ($this->estrutura as $moduleName => $vController) {
        $data = '{';
        $data .= '"text": "' . $moduleName . '",';
        $data .= '"id": "modulo:' . $moduleName . '",';
        $data .= '"children": [';
        foreach ($vController as $controllerName => $vAction) {
            $data .= '{
                            "text": "' . $controllerName . '",
                            "id": "modulo:' . $moduleName . ',controller:' . $controllerName . '",
                            "state": {
                                "selected": false
                            },
                            "children": [';
            foreach ($vAction as $actionName) {

                $data .= '{';
                $data .= '"text": "' . $actionName['action'] . '",
                            "id": "' . $moduleName . ',' . $controllerName . ',' . $actionName['action'] . '",
                            "icon" : "fa fa-file icon-state-warning jstree-themeicon-custom",
                                            "state": {';
                if ($actionName['permissao']) {
                    $data .= '"selected": true';
                }
                $data .= '}';
                $data .= '},';
            }
            $data .= ']';
            $data .= '},';
        }
        $data .= ']';
        $data .= '}';
    }
}
?>
<script type="text/javascript">
    $(function () {

        $('#tree_pagina').jstree({
            'plugins': ["wholerow", "checkbox", "types"],
            'core': {
                "themes": {
                    "responsive": false
                },
                'data': [<?=$data?>],

            },
            "types": {
                "default": {
                    "icon": "fa fa-folder icon-state-warning icon-lg"
                },
                "file": {
                    "icon": "fa fa-file icon-state-warning icon-lg"
                }
            }
        });
        $('#tree_pagina')
        // listen for event
            .on('select_node.jstree', function (e, data) {
                var i, j, r = [];
                $.post("/painel/permissao/ajaxpermissao", {paginas: $("#tree_pagina").jstree('get_selected')},
                    function (data) {

                    }
                );

            })
            // create the instance
            .jstree();
        $('#tree_pagina')
        // listen for event
            .on('deselect_node.jstree', function (e, data) {
                var i, j, r = [];
                $.post("/painel/permissao/ajaxpermissao", {paginas: $("#tree_pagina").jstree('get_selected')},
                    function (data) {

                    }
                );

            })
            // create the instance
            .jstree();

    });
</script>
<div class="row">
    <div class="col-xs-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-settings font-dark"></i>
                    <span class="caption-subject bold uppercase">Páginas</span>
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                <div id="tree_pagina" class="tree-demo">

                </div>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>