<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.7
Version: 4.7
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->

<head>
    <meta charset="utf-8"/>
    <title>LOGIN ÁREA ADMINISTRATIVA | <?= Zend_Registry::get('CLIENTE') ?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta
        content="#1 selling multi-purpose bootstrap admin theme sold in themeforest marketplace packed with angularjs, material design, rtl support with over thausands of templates and ui elements and plugins to power any type of web applications including saas and admin dashboards. Preview page of Theme #4 for "
        name="description"/>
    <meta content="" name="author"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet"
          type="text/css"/>
    <link href="/painel_template/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet"
          type="text/css"/>
    <link href="/painel_template/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet"
          type="text/css"/>
    <link href="/painel_template/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet"
          type="text/css"/>
    <link href="/painel_template/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet"
          type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="/painel_template/assets/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css"/>
    <link href="/painel_template/assets/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet"
          type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="/painel_template/assets/global/css/components-rounded.min.css" rel="stylesheet" id="style_components"
          type="text/css"/>
    <link href="/painel_template/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME GLOBAL STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href="/painel_template/assets/pages/css/login.min.css" rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL STYLES -->
    <!-- BEGIN THEME LAYOUT STYLES -->
    <link href="/painel_template/assets/global/plugins/bootstrap-sweetalert/sweetalert.css" rel="stylesheet" type="text/css" />

    <!-- END THEME LAYOUT STYLES -->
    <link rel="icon" href="/site/assets/icon/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/site/assets/icon/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/site/assets/icon/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/site/assets/icon/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/site/assets/icon/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/site/assets/icon/apple-touch-icon-60x60.png" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/site/assets/icon/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/site/assets/icon/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/site/assets/icon/apple-touch-icon-152x152.png" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-196x196.png" sizes="196x196" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-16x16.png" sizes="16x16" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-128.png" sizes="128x128" />
    <meta name="application-name" content="&nbsp;"/>
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="/site/assets/icon/mstile-144x144.png" />
    <meta name="msapplication-square70x70logo" content="/site/assets/icon/mstile-70x70.png" />
    <meta name="msapplication-square150x150logo" content="/site/assets/icon/mstile-150x150.png" />
    <meta name="msapplication-wide310x150logo" content="/site/assets/icon/mstile-310x150.png" />
    <meta name="msapplication-square310x310logo" content="/site/assets/icon/mstile-310x310.png" />
</head>
<!-- END HEAD -->

<link href="/site/assets/css/login.css" rel="stylesheet" type="text/css"/>

<body class=" login">
<!-- BEGIN LOGO -->
<div class="logo">
    <a href="/painel/">
        <img src="/site/assets/icon/favicon-96x96.png" alt=""/> </a>
</div>
<!-- END LOGO -->
<!-- BEGIN LOGIN -->
<div class="content">
    <!-- BEGIN LOGIN FORM -->
    <div class="errors">
    </div><form class="login-form" action="" method="post">
        <h3 class="form-title font-green">LOGIN</h3>
        <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button>
            <span> Digite um usuário e senha válidos. </span>
        </div>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon">
                <i class="fa fa-envelope font-blue-chambray"></i>
                <input class="form-control form-control-solid placeholder-no-fix email required" type="text" autocomplete="off"
                       placeholder="Email" name="email" id="email"/>
            </div>
            <?=$this->formErrors($this->form->email->getMessages())?>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Senha</label>
            <div class="input-icon">
                <i class="fa fa-lock font-blue-chambray"></i>
                <input class="form-control form-control-solid placeholder-no-fix required" type="password" autocomplete="off"
                       placeholder="Senha" name="senha" id="senha"/>
            </div>
            <?=$this->formErrors($this->form->senha->getMessages())?>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn green uppercase">Login</button>
            <a href="javascript:;" id="forget-password" class="forget-password">Esqueceu sua senha?</a>
        </div>
    </form>
    <!-- END LOGIN FORM -->
    <!-- BEGIN FORGOT PASSWORD FORM -->
    <form class="forget-form" action="/painel/auth/recuperasenha" method="post">
        <h3 class="font-green">Esqueceu sua senha ?</h3>
        <p> Digite seu email abaixo e registre uma nova senha. </p>
        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon">
                <i class="fa fa-envelope font-blue-chambray"></i>
                <input class="form-control form-control-solid placeholder-no-fix required email" type="text" autocomplete="off"
                       placeholder="Email" name="email" id="email-esqueceu"/>
            </div>
        </div>
        <div class="form-actions">
            <button type="button" id="back-btn" class="btn green btn-outline">Voltar</button>
            <button type="submit" class="btn btn-success uppercase pull-right">Enviar</button>
        </div>
    </form>

    <!-- END FORGOT PASSWORD FORM -->
</div>
<!--<div class="copyright"> 2014 © Metronic. Admin Dashboard Template. </div>-->
<!--[if lt IE 9]>
<script src="/painel_template/assets/global/plugins/respond.min.js"></script>
<script src="/painel_template/assets/global/plugins/excanvas.min.js"></script>
<script src="/painel_template/assets/global/plugins/ie8.fix.min.js"></script>
<![endif]-->
<!-- BEGIN CORE PLUGINS -->
<script src="/painel_template/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js"
        type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js"
        type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="/painel_template/assets/global/plugins/jquery-validation/js/jquery.validate.min.js"
        type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/jquery-validation/js/localization/messages_pt_BR.js"
        type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/jquery-validation/js/additional-methods.min.js"
        type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="/painel_template/assets/global/scripts/app.min.js" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/painel_template/assets/global/plugins/bootstrap-sweetalert/sweetalert.min.js" type="text/javascript"></script>
<?php
if ($this->messages) {
    echo $this->partial('includes/FlashMessenger.phtml', 'painel', array('mensagem' => $this->messages));
}
?>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME LAYOUT SCRIPTS -->
<!-- END THEME LAYOUT SCRIPTS -->
<script src="/site/assets/js/painel.js" type="text/javascript"></script>

</body>

</html>