<div class="row">
    <div class="col-xs-12">
        <?= $this->cadastrar('/painel/grupo/inserealtera/') ?>
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-settings font-dark"></i>
                    <span class="caption-subject bold uppercase">Grupos de usuários</span>
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                <?php
                if ($this->voRegistro) {
                    ?>
                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_1">
                        <thead>
                        <tr>
                            <th class="all">Grupo</th>
                            <th class="all sorting_disabled opcoes-header">Opções</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->voRegistro as $oRegistro) {
                            ?>
                            <tr>
                                <td>
                                    <?= $oRegistro->nome ?>
                                </td>
                                <td class="opcoes-tbody">
                                    <?php
                                    if ($oRegistro->id > 1) {
                                        ?>
                                        <?= $this->editar('/painel/grupo/inserealtera/id/' . $oRegistro->id) ?>
                                        <?= $this->excluir('/painel/grupo/excluir/id/' . $oRegistro->id) ?>
                                        <?php
                                    }
                                    ?>

                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>
                    <?
                }
                ?>

            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
