<div class="row">
    <div class="col-xs-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-settings font-dark"></i>
                    <span class="caption-subject bold uppercase">Detalhe do log #<?= $this->oLog->id ?></span>
                </div>
                <div class="tools"></div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>

                        <th>Campos</th>
                        <th>Informação</th>


                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Usuário</td>
                        <td><?= $this->oLog->findParentRow('Db_UsuUsuario')->nome ?></td>
                    </tr>
                    <tr>
                        <td>Operação</td>
                        <td><?= $this->oLog->findParentRow('Db_LogTipo')->nome ?></td>
                    </tr>
                    <tr>
                        <td>Tabela</td>
                        <td><?= $this->oLog->tabela ?></td>
                    </tr>
                    <tr>
                        <td>Data</td>
                        <td><?= Plugin_Util::dataHoraToSite($this->oLog->data) ?></td>
                    </tr>
                    <tr>
                        <td>Dados</td>
                        <td>
                            <?
                            $xml = new SimpleXMLElement($this->oLog["dados"]);

                            ?>
                            <textarea rows="10" cols="50">
                  	<?= $xml->asXML() ?>
                  </textarea>

                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>

<? if ($this->oLog) {
    ?>

    <?

} else {
    ?>
    Não há logs registrados
    <?
} ?>



<?php
