<div class="row">
    <div class="col-xs-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-settings font-dark"></i>
                    <span class="caption-subject bold uppercase">Logs do sistema</span>
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                <?php
                if ($this->voRegistro) {
                    ?>
                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_1">
                        <thead>
                        <tr>
                            <th class="all">Usuário</th>
                            <th class="desktop">Operação</th>
                            <th class="desktop">Tabela</th>
                            <th class="all">Data</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($this->voRegistro as $oRegistro) {
                            ?>
                            <tr>
                                <td>
                                    <a href="<?= $this->Permissao('/painel/log/exibir/id/' . $oRegistro->id) ?>">
                                        <?= $oRegistro->findParentRow('Db_UsuUsuario')->nome ?>
                                    </a>
                                </td>
                                <td>
                                    <?= $oRegistro->findParentRow('Db_LogTipo')->nome ?>
                                </td>
                                <td>
                                    <?= $oRegistro->tabela ?>
                                </td>
                                <td>
                                    <?= Plugin_Util::dataHoraToSite($oRegistro->data) ?>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>
                    <?
                }
                ?>

            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
