<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.7
Version: 4.7
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->

<head>
    <meta charset="utf-8" />
    <title>Painel administrativo | <?=Zend_Registry::get('CLIENTE')?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="#1 selling multi-purpose bootstrap admin theme sold in themeforest marketplace packed with angularjs, material design, rtl support with over thausands of templates and ui elements and plugins to power any type of web applications including saas and admin dashboards. Preview page of Theme #4 for blank page layout"
          name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="/painel_template/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/painel_template/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/painel_template/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/painel_template/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="/painel_template/assets/global/css/components-rounded.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="/painel_template/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <!-- END THEME GLOBAL STYLES -->
    <!-- BEGIN THEME LAYOUT STYLES -->
    <link href="/painel_template/assets/layouts/layout4/css/layout.min.css" rel="stylesheet" type="text/css" />
    <link href="/painel_template/assets/layouts/layout4/css/themes/light.min.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="/painel_template/assets/layouts/layout4/css/custom.min.css" rel="stylesheet" type="text/css" />

    <link href="/painel_template/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
    <link href="/painel_template/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />

    <link href="/painel_template/assets/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
    <link href="/painel_template/assets/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />

    <link href="/painel_template/assets/global/plugins/bootstrap-sweetalert/sweetalert.css" rel="stylesheet" type="text/css" />
    <link href="/site/assets/css/painel.css" rel="stylesheet" type="text/css"/>

    <script src="/painel_template/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="/painel_template/assets/global/plugins/jstree/dist/jstree.min.js" type="text/javascript"></script>
    <link href="/painel_template/assets/global/plugins/jstree/dist/themes/default/style.min.css" rel="stylesheet" type="text/css" />

    <!-- END THEME LAYOUT STYLES -->
    <link rel="icon" href="/site/assets/icon/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/site/assets/icon/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/site/assets/icon/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/site/assets/icon/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/site/assets/icon/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/site/assets/icon/apple-touch-icon-60x60.png" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/site/assets/icon/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/site/assets/icon/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/site/assets/icon/apple-touch-icon-152x152.png" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-196x196.png" sizes="196x196" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-16x16.png" sizes="16x16" />
    <link rel="icon" type="image/png" href="/site/assets/icon/favicon-128.png" sizes="128x128" />
    <meta name="application-name" content="&nbsp;"/>
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="/site/assets/icon/mstile-144x144.png" />
    <meta name="msapplication-square70x70logo" content="/site/assets/icon/mstile-70x70.png" />
    <meta name="msapplication-square150x150logo" content="/site/assets/icon/mstile-150x150.png" />
    <meta name="msapplication-wide310x150logo" content="/site/assets/icon/mstile-310x150.png" />
    <meta name="msapplication-square310x310logo" content="/site/assets/icon/mstile-310x310.png" />
<!-- END HEAD -->

<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="/painel">
                <img src="/site/assets/icon/apple-touch-icon-60x60.png" alt="logo" class="logo-default" /> </a>
            <div class="menu-toggler sidebar-toggler">
                <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
            </div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN PAGE TOP -->
        <div class="page-top">
            <!-- BEGIN TOP NAVIGATION MENU -->
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <!-- BEGIN USER LOGIN DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    <li class="dropdown dropdown-user dropdown-dark">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <span class="username username-hide-on-mobile"> <?=Plugin_Auth::getInstance()->getIdentity()->nome?> </span>
                            <!-- DOC: Do not remove below empty space(&nbsp;) as its purposely used -->
                            <?
                            if(Plugin_Auth::getInstance()->getIdentity()->arquivo && $_SERVER['DOCUMENT_ROOT'].'/data/'.Plugin_Auth::getInstance()->getIdentity()->arquivo){
                                $arquivo = '/data/'.Plugin_Auth::getInstance()->getIdentity()->arquivo;
                            }else{
                                $arquivo = "/painel_template/assets/layouts/layout4/img/avatar.png";
                            }
                            ?>
                            <img alt="" class="img-circle" src="<?=$arquivo?>" /> </a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="<?=$this->Permissao('/painel/usuario/alterasenha')?>">
                                    <i class="icon-key"></i> Alterar senha </a>
                            </li>
                            <li class="divider"> </li>
                            <li>
                                <a href="/painel/auth/logout">
                                    <i class="icon-key"></i> Sair </a>
                            </li>
                        </ul>
                    </li>
                    <!-- END USER LOGIN DROPDOWN -->
                </ul>
            </div>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END PAGE TOP -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
<!-- BEGIN HEADER & CONTENT DIVIDER -->
<div class="clearfix"> </div>
<!-- END HEADER & CONTENT DIVIDER -->
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!-- BEGIN SIDEBAR -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
            <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
            <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
            <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
            <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
            <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
            <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <ul class="page-sidebar-menu   " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                <li class="nav-item start <?=$this->bInicio?"active":""?>">
                    <a href="/painel" class="nav-link nav-toggle">
                        <i class="icon-home"></i>
                        <span class="title">Início</span>
                    </a>
                </li>

                <li class="heading">
                    <h3 class="uppercase">Conteúdo</h3>
                </li>
                <li class="nav-item  <?=$this->bPag?"active":""?>">
                    <a href="/painel/pagina" class="nav-link nav-toggle">
                        <i class="icon-docs"></i>
                        <span class="title">Páginas</span>
                    </a>
                </li>
                <li class="nav-item  <?=$this->bBannerH?"active":""?>">
                    <a href="/painel/banner" class="nav-link nav-toggle">
                        <i class="icon-frame"></i>
                        <span class="title">Banner Home</span>
                    </a>
                </li>
                <li class="heading">
                    <h3 class="uppercase">Administração</h3>
                </li>
                <li class="nav-item  <?=$this->bGrupo?"active":""?>">
                    <a href="/painel/grupo" class="nav-link nav-toggle">
                        <i class="icon-users"></i>
                        <span class="title">Grupo de usuários</span>
                    </a>
                </li>
                <li class="nav-item  <?=$this->bUsu?"active":""?>">
                    <a href="/painel/usuario" class="nav-link nav-toggle">
                        <i class="icon-user"></i>
                        <span class="title">Usuários</span>
                    </a>
                </li>
                <li class="<?= ($this->bConfig ? 'active' : '') ?>">

                    <a href="javascript:;">
                        <i class="icon-settings"></i>
                        <span class="title">Permissões</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="<?= ($this->bPag ? 'active' : '') ?>">
                            <a href="<?= $this->permissao('/painel/permissao/pagina') ?>">
                                <i class="icon-doc"></i>
                                Páginas</a>
                        </li>
                        <li class="<?= ($this->bPerPag ? 'active' : '') ?>">
                            <a href="<?= $this->permissao('/painel/permissao/permissaogrupo') ?>">
                                <i class="icon-lock"></i>
                                Permissões de grupos</a>
                        </li>
                        <li class="<?= ($this->bLog ? 'active' : '') ?>">
                            <a href="<?= $this->permissao('/painel/log/') ?>">
                                <i class="icon-docs"></i>
                                Logs do sistema</a>
                        </li>
                    </ul>
                </li>
                <li class="<?= ($this->bConfigSite ? 'active' : '') ?>">

                    <a href="javascript:;">
                        <i class="icon-globe"></i>
                        <span class="title">Configurações do site</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="<?= ($this->bGeral ? 'active' : '') ?>">
                            <a href="<?= $this->permissao('/painel/configuracao/geral') ?>">
                                <i class="icon-question"></i>
                                Configurações gerais</a>
                        </li>
                        <li class="<?= ($this->bSeo ? 'active' : '') ?>">
                            <a href="<?= $this->permissao('/painel/configuracao/seo') ?>">
                                <i class="icon-link"></i>
                                SEO</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- END SIDEBAR MENU -->
        </div>
        <!-- END SIDEBAR -->
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <!-- BEGIN PAGE HEAD-->
            <div class="page-head">
                <!-- BEGIN PAGE TITLE -->
                <!--<div class="page-title">
                    <h1>Blank Page Layout
                        <small>blank page layout</small>
                    </h1>
                </div>-->
                <!-- END PAGE TITLE -->
            </div>
            <!-- END PAGE HEAD-->
            <!-- BEGIN PAGE BASE CONTENT -->
            <?= $this->layout()->content ?>
            <!-- END PAGE BASE CONTENT -->
        </div>
        <!-- END CONTENT BODY -->
    </div>
    <!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner"> <?=date('Y')?> &copy; <?=Zend_Registry::get('CLIENTE')?>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->
<!--[if lt IE 9]>
<script src="/painel_template/assets/global/plugins/respond.min.js"></script>
<script src="/painel_template/assets/global/plugins/excanvas.min.js"></script>
<script src="/painel_template/assets/global/plugins/ie8.fix.min.js"></script>
<![endif]-->
<!-- BEGIN CORE PLUGINS -->

<script src="/painel_template/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="/painel_template/assets/global/scripts/app.min.js" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN THEME LAYOUT SCRIPTS -->
<script src="/painel_template/assets/layouts/layout4/scripts/layout.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/layouts/layout4/scripts/demo.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/layouts/global/scripts/quick-nav.min.js" type="text/javascript"></script>
<!-- END THEME LAYOUT SCRIPTS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/painel_template/assets/global/plugins/jquery-validation/js/jquery.validate.min.js"
        type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/jquery-validation/js/localization/messages_pt_BR.js"
        type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/jquery-validation/js/additional-methods.min.js"
        type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/bootstrap-sweetalert/sweetalert.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/painel_template/assets/pages/scripts/table-datatables-responsive.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
<script src="/painel_template/assets/pages/scripts/components-select2.js" type="text/javascript"></script>
<script src="/painel_template/assets/global/plugins/ckeditor/ckeditor.js" type="text/javascript"></script>
<?php
if ($this->messages) {
    echo $this->partial('includes/FlashMessenger.phtml', 'painel', array('mensagem' => $this->messages));
}
?>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME LAYOUT SCRIPTS -->
<!-- END THEME LAYOUT SCRIPTS -->
<script src="/site/assets/js/painel.js" type="text/javascript"></script>
</body>

</html>