<div class="portlet light bordered form-fit">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-equalizer font-green-haze"></i>
            <span class="caption-subject font-green-haze bold uppercase"><?= $this->form->getAttrib('name') ?> | <?=$this->oRegistro->nome?></span>
            <span class="caption-helper">Preencha os campos do formulário</span>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <?= $this->render('includes/form.phtml') ?>
        <!-- END FORM-->
    </div>
</div>